---
- name: Ensure that the `network-scripts` package is installed
  ansible.builtin.package:
    name: "network-scripts"
    state: present
  become: true

- name: Ensure that the `network` service has been selected over `NetworkManager`
  ansible.builtin.service:
    name: "network"
    enabled: true
  become: true

- name: Ensure the interface scripts are present within `/etc/sysconfig/network-scripts/`
  ansible.builtin.copy:
    src: "files/{{ item }}"
    dest: "/etc/sysconfig/network-scripts/{{ item }}"
    mode: "+x"
  with_items:
    - ifup-vxlan
    - ifdown-vxlan
  become: true
