#!/bin/bash

. /etc/init.d/functions

cd /etc/sysconfig/network-scripts
. ./network-functions

[ -f ../network ] && . ../network

CONFIG=${1}

need_config ${CONFIG}

source_config

/etc/sysconfig/network-scripts/ifup ${PHYS_DEV}

ip link add ${DEVICE} type vxlan \
        id ${VNI} \
        group ${GROUP} \
        ttl ${TTL:-10} \
        dev ${PHYS_DEV} \
        dstport ${PORT:-4789}

/etc/sysconfig/network-scripts/ifup-eth ${DEVICE}